index:
  rootDir: D:\a影视\gif
  isRecall: 1
  errimg: ./plugins/suibian-plugin/res/img/空空如也.png
  recallTime: 60000
reslist:
  - ABP-596.gif
  - ADN-018.gif
  - APNS-025#.gif
  - AVOP-227.gif
  - DDK-134.gif
  - DDK-160.gif
  - FC2-PPV-4547860#(1).gif
  - FC2-PPV-4547860#(2).gif
  - FC2-PPV-4547860#(3).gif
  - GACHI-1151#.gif
  - GACHI-805.gif
  - GANA-1459#.gif
  - GAR-333.gif
  - GVG-262.gif
  - HND-169.gif
  - IBW-563Z.gif
  - KAGP-019#.gif
  - KAWD-567#.gif
  - MDS-807#.gif
  - MIDE-476#.gif
  - MIGD-745.gif
  - NNPJ-046.gif
  - OVG-023.gif
  - RDT-171.gif
  - RKI-445.gif
  - SHKD-738#.gif
  - SKY-247#.gif
  - SNIS-786.gif
  - SSNI-025#.gif
  - TYOD-265#.gif
